### ISSUE TITLE
Confirm MRW_ENHANCED_GROUPING_NO_MIRRORING is set correctly.

### ISSUE THREAD

**Issue by williamspatrick** [open-power/garrison-xml#6]
See open-power/op-build#493 .

**Comment by stewart-ibm** [comment]
This is gating our op-build v1.10 release and has caused it to be delayed (so far) 5 weeks. Please review and merge ASAP. (be that by @bwmashak or @Erich-Hauptli )

**Comment by Erich-Hauptli** [comment]
This is set currently set properly for Garrison.  This was found on Garrison and then integrated on April 6.

Garrison.xml content
 <attribute>
        <id>MRW_ENHANCED_GROUPING_NO_MIRRORING</id>
        <default>false</default>
    </attribute>
